export const routes = {
  home: "/",
  login: "/auth/login",
  register: "/auth/register",
  otp: "/auth/otp",
  profile: "/user/profile",
  communitySearch: "/community/search",
  communityDetails: "/community/details",
  communityAccessRequest: "/community/access-request",
  communityRequestStatus: "/community/request-status",
  communityDashboard: "/community/dashboard",
  feed: "/posts/feed",
  createPost: "/posts/create",
  myPosts: "/posts/my",
  postDetails: "/posts/details",
  events: "/events/list",
  createEvent: "/events/create",
  eventDetails: "/events/details",
  eventCalendar: "/events/calendar",
  eventReminder: "/events/reminder",
  adminDashboard: "/admin/dashboard",
  adminAccessRequests: "/admin/access-requests",
  adminAccessRequestReview: "/admin/access-request-review",
  adminPostApprovals: "/admin/post-approvals",
  adminPostReview: "/admin/post-review",
  notifications: "/notifications",
  settings: "/settings"
} as const;
